defmodule Pointex.Repo.Migrations.AddNopedToParticipant do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ash_participants) do
      modify :shortlist, {:array, :text}, default: []
      add :noped, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:ash_participants) do
      remove :noped
      modify :shortlist, {:array, :text}, default: nil
    end
  end
end
