defmodule Pointex.Repo.Migrations.AddIdentityToParticipant do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:ash_participants, [:account_id, :watch_party_id],
             name: "ash_participants_one_participant_per_account_per_wp_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ash_participants, [:account_id, :watch_party_id],
                     name: "ash_participants_one_participant_per_account_per_wp_index"
                   )
  end
end
