defmodule Pointex.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:songs), :season_id, to: :year

    drop constraint(:songs, "songs_season_id_fkey")

    alter table(:songs) do
      modify :year,
             references(:ash_seasons,
               column: :year,
               name: "songs_year_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    execute("ALTER TABLE songs alter CONSTRAINT songs_year_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:songs, "songs_year_fkey")

    alter table(:songs) do
      modify :season_id,
             references(:ash_seasons,
               column: :year,
               name: "songs_season_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    rename table(:songs), :year, to: :season_id
  end
end
