defmodule Pointex.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ash_shows, primary_key: false) do
      add :kind, :text, null: false, primary_key: true

      add :year,
          references(:ash_seasons,
            column: :year,
            name: "ash_shows_year_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:ash_shows, "ash_shows_year_fkey")

    drop table(:ash_shows)
  end
end
