defmodule Pointex.Repo.Migrations.AddShortlistToParticipant do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ash_participants) do
      add :shortlist, {:array, :text}
    end
  end

  def down do
    alter table(:ash_participants) do
      remove :shortlist
    end
  end
end
