defmodule Pointex.Repo.Migrations.AddFinalVoteSubmittedToParticipant do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ash_participants) do
      add :final_vote_submitted, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:ash_participants) do
      remove :final_vote_submitted
    end
  end
end