defmodule Pointex.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:songs) do
      add :order_in_sf1, :bigint
      add :order_in_sf2, :bigint
      add :order_in_final, :bigint
      add :final_place, :bigint
    end
  end

  def down do
    alter table(:songs) do
      remove :final_place
      remove :order_in_final
      remove :order_in_sf2
      remove :order_in_sf1
    end
  end
end
