defmodule Pointex.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:songs, primary_key: false) do
      add :country, :text, null: false, primary_key: true
      add :flag, :text, null: false
      add :artist, :text, null: false
      add :name, :text, null: false
      add :img, :text, null: false

      add :season_id,
          references(:ash_seasons,
            column: :year,
            name: "songs_season_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    alter table(:ash_watch_parties) do
      modify :owner_id, :uuid, null: false
    end
  end

  def down do
    alter table(:ash_watch_parties) do
      modify :owner_id, :uuid, null: true
    end

    drop constraint(:songs, "songs_season_id_fkey")

    drop table(:songs)
  end
end
