defmodule Pointex.Repo.Migrations.AddAuth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute("DELETE FROM ash_participants")
    execute("DELETE FROM ash_watch_parties")
    execute("DELETE FROM ash_accounts")

    alter table(:ash_accounts) do
      add :email, :citext, null: false
    end

    create unique_index(:ash_accounts, [:email], name: "ash_accounts_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:ash_accounts, [:email], name: "ash_accounts_unique_email_index")

    alter table(:ash_accounts) do
      remove :email
    end

    drop table(:tokens)
  end
end
