defmodule Pointex.Repo.Migrations.MakeAccountsNameNullable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ash_accounts) do
      remove :confirmed_at
      modify :name, :text, null: true
    end
  end

  def down do
    alter table(:ash_accounts) do
      modify :name, :text, null: false
      add :confirmed_at, :utc_datetime_usec
    end
  end
end
