defmodule Pointex.Repo.Migrations.AllowPartialEntryForSongs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:songs) do
      modify :img, :text, null: true
      modify :name, :text, null: true
      modify :artist, :text, null: true
    end
  end

  def down do
    alter table(:songs) do
      modify :artist, :text, null: false
      modify :name, :text, null: false
      modify :img, :text, null: false
    end
  end
end
